

if Rails.env.production?  
	ENV["AWS_ACCESS_KEY_ID"] = 'AKIAI2J75VJLDQRV5EHQ'
	ENV["AWS_SECRET_ACCESS_KEY"] = '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'
	ENV["AWS_S3_BUCKET"] = 'vinylfabrikken-stage'	
else
	ENV["AWS_ACCESS_KEY_ID"] = 'AKIAI2J75VJLDQRV5EHQ'
	ENV["AWS_SECRET_ACCESS_KEY"] = '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'
	ENV["AWS_S3_BUCKET"] = 'vinylfabrikken-dev'
end